### ISSUE TITLE
Analytics not being tracked.

### ISSUE THREAD

**Issue by dakamojo** [ctacke/opennetcf#3]
I'm not seeing my data getting tracked.  My code is pretty simple.

		private void InitGoogleAnalytics()
		{
			AnalyticsService = new AnalyticsService(TrackingId, null, "Woot Dashboard", GetAppVersion());
			AnalyticsService.TrackSessionStart();

		}

		public void TrackEvent(string category, string action, string label)
		{
			AnalyticsService.TrackEvent(category, action, label);
		}

I call InitGoogleAnalytics in my App class constructor and I call TrackEvent from various places in my app.  Not only am I not seeing the events logged in GA, but I am not seeing the Debug message from line 228 in AnalyticsService.

Any ideas?

Is there any way to trace within a nuget?  If not I will clone the project and include the code so that I can debug.

**Comment by ctacke** [comment]
No idea if you can step into a NuGet - I just use the source.  You won't see any internal debug messages becasue the NuGet package binaries are all Release configuration.

**Comment by dakamojo** [comment]
I cloned the project and am working on figuring out my problem.  On another note, any idea why the package installed in Xamarin Studio still installs the .2 version?  It doesn't show the .3 version.

**Comment by dakamojo** [comment]
Here's what I have found.  It appears to be the way GA handles sessions.  Its not an issue with the library.  In our app we only track events, not pages.  Using the native GA iOS and Android libraries once the first event is logged, a session starts.  Apparently using the HTTP interface (which this library is using) you must track a page in order for the session to start.  So I have switched to tracking pages.  This issue can be closed.

**Comment by ctacke** [comment]
Hmm, strange.  If you start a session explicitly (with a call to `TrackSessionStart`) does that get it primed?

**Comment by dakamojo** [comment]
I traced the steps and I can see that it sends the TrackSessionStart payload to GA and receives a success response.  The GA reports are showing Users and Events.  But the session related data like session count, session length, etc are all 0.  Once I changed from tracking events to tracking pages all the session data got populated (I'm still calling TrackSessionStart).
